version: "3.8"

services:

  web:
    build: ./web
    volumes:
      - image_dir:/images
    ports:
      - "8000:8000"

  automosaic:
    build: ./automosaic
    volumes:
      - image_dir:/images
      - dataset_dir:/datasets
    environment:
      - PYTHONUNBUFFERED=1

  storage:
    build: ./storage
    volumes:
      - image_dir:/images
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  image_dir:
  dataset_dir:
